on: [push, pull_request]

jobs:
  gha-sandbox-ts:
    runs-on: ubuntu-latest
    name: A sandbox job
    steps:
    - uses: a2ikm/gha-sandbox-ts@v1.1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run lint

  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run format-check
